name: CoinMarket
version: '${version}'
main: io.github.hibixby.coinmarket.CoinMarket
api-version: 1.19
authors: [ Hey_Siri_ ]
description: trading cryptocurrency
commands:
  coinprice:
    description: get price of coin
    aliases: [cp,cprice,price]
    usage: /<command>
