name: SpigotPluginStudy
version: '${version}'
main: io.github.hibixby.spigotpluginstudy.SpigotPluginStudy
api-version: 1.19
authors: [ Hey_Siri_ ]
description: Spigot plugin study
commands:
  price:
    description: get price of coin
    aliases: [cp,coinprice]
    usage: /<command>
